version: '3.8'
services:
  db:
    image: mysql:8.0.36
    container_name: norwegian-rental
    environment:
      - MYSQL_ROOT_PASSWORD=NorwegianPassword123
      - MYSQL_DATABASE=rental
      - MYSQL_USER=RudolfTheRed
      - MYSQL_PASSWORD=TheRedNose1001
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - "127.0.0.1:6000:3306"
    networks:
      - rental-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    image: ntnu/docker-demo:1.0
    container_name: my-spring-app
    restart: always
    ports:
      - "[::]:8080:8081"  # IPv6
      - "0.0.0.0:8080:8081"  # IPv4
    depends_on:
      db:
        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/rental?createDatabaseIfNotExist=true
      - SPRING_DATASOURCE_USERNAME=RudolfTheRed
      - SPRING_DATASOURCE_PASSWORD=TheRedNose1001
    networks:
      - rental-network

networks:
  rental-network:
    driver: bridge

volumes:
  mysql-data:
