version: '3.8'
services:
  db:
    image: mysql:8.0.36
    container_name: norwegian-rental
    environment:
      - MYSQL_ROOT_PASSWORD=NorwegianPassword123
      - MYSQL_DATABASE=rental
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - "6000:3306"
    networks:
      - rental-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    image: ntnu/docker-demo:1.0
    container_name: my-spring-app
    ports:
      - "8080:8081"  # Maps host port 8080 to container port 8081 (per application.properties)
    depends_on:
      db:
        condition: service_healthy
    networks:
      - rental-network

networks:
  rental-network:
    driver: bridge

volumes:
  mysql-data: